DECLARE @SQL NVARCHAR(1000)
DECLARE @Codigo VARCHAR(20)
DECLARE ATUALIZA_ATIVOS CURSOR FOR
SELECT CÓDIGOS FROM Ativos
OPEN ATUALIZA_ATIVOS
FETCH NEXT FROM ATUALIZA_ATIVOS

INTO @Codigo WHILE @@FETCH_STATUS = 0

BEGIN
	SELECT @SQL = 'CREATE TABLE [CONSOL_' + @Codigo + '](
		[ID] INT, [CORRETORA] NUMERIC(18, 0) ,[COMPROU] NUMERIC(18, 0), [VENDEU] NUMERIC(18, 0), [DATA DA LEITURA] DATETIME, [ACUMULA��O] NUMERIC(18, 0)
	)'
	
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONSOL_'+ @Codigo + ']') AND type in (N'U'))
	begin
	declare @sqldel  nvarchar(50)
	 select @sqldel = 'DROP TABLE ' + '[dbo].[CONSOL_'+ @Codigo + ']'
	 EXEC SP_EXECUTESQL  @sqldel
	end
	
	EXEC SP_EXECUTESQL @SQL
	FETCH NEXT FROM ATUALIZA_ATIVOS
	
	INTO @Codigo

END
CLOSE ATUALIZA_ATIVOS
DEALLOCATE ATUALIZA_ATIVOS
GO;